language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost:5432/registration_webapp
     
node_js:  
   - "8.9.4"
        
before_script:
  - psql -c 'create database registration_webapp;' -U postgres 
  - psql -U postgres -d registration_webapp -a -f table.sql